# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Witmoyl
tagline:             'Always confusing'
description:         'Welcome! I am David, a programmer who likes math, photography, philosophy.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
